import { defineConfig } from "astro/config";
import vue from "@astrojs/vue";
import tailwindcss from "@tailwindcss/vite";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import preact from "@astrojs/preact";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import { remarkMermaidBlocks } from "./src/plugins/rehype-mermaid-blocks.mjs";
// Auto-generated by site-generator — contains page redirects and sitemap locale config
import siteConfig from "./src/website.redirects.mjs";

// Site URL: set SITE_URL env var in CI for correct sitemap generation.
const siteUrl = process.env.SITE_URL || "http://localhost:4321";
// Base path: set ASTRO_BASE for preview builds served under a subpath (e.g. /storage/site-builds/...).
// Leave unset for production builds served from root.
const astroBase = process.env.ASTRO_BASE; // undefined → Astro default ("/")

// When a base path is set, Astro prefixes redirect *sources* automatically but
// does NOT prefix redirect *destinations*. Fix that here so e.g. "/home" →
// "/en/home" becomes "/home" → "/site1/en/home" when ASTRO_BASE="/site1".
const base = astroBase ? astroBase.replace(/\/$/, "") : "";
const redirects = base
  ? Object.fromEntries(
      Object.entries(siteConfig.redirects).map(([from, to]) => [from, base + to])
    )
  : siteConfig.redirects;

export default defineConfig({
  redirects,
  // srcDir defaults to "./src" — generator writes pages/data/content into src/
  outDir: "./dist",
  publicDir: "./public",
  site: siteUrl,
  ...(astroBase ? { base: astroBase } : {}),

  server: {
    host: "localhost",
    port: 4321,
  },

  image: {
    service: {
      entrypoint: "astro/assets/services/sharp",
    },
  },

  integrations: [
    preact({
      include: ["**/preact/*", "**/icons/*"],
      compat: true,
    }),
    vue(),
    mdx({
      extendMarkdownConfig: false,
      remarkPlugins: [remarkMath, remarkMermaidBlocks],
      rehypePlugins: [
        [rehypeKatex, {}],
      ],
    }),
    sitemap({
      i18n: {
        defaultLocale: siteConfig.defaultLocale,
        locales: siteConfig.locales,
      },
    }),
  ],

  markdown: {
    remarkPlugins: [remarkMath, remarkMermaidBlocks],
    rehypePlugins: [
      [rehypeKatex, {}],
    ],
  },

  vite: {
    plugins: [tailwindcss()],
    resolve: {
      alias: {
        "~/": new URL("./src/", import.meta.url).pathname,
      },
    },
  },
});
